server:
  port: 17284

spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://localhost:3306/yls
    username: swcamp
    password: swcamp
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true


mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    com:
      eat:
        today:
          member:
            query: debug  # 로그찍기


