server:
  port: 17284

spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/yls
    username: swcamp
    password: swcamp

mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true  # DTO 에서 이름이랑 xml 파일에서 이름이랑 형식 안맞는거 매핑해줌
logging:
  level:
    com:
      eat:
        today:
          member:
            query: debug
